<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                                      ->prependFile($this->basePath() . '/js/jquery.min.js') ?>

    </head>
    <body>
    	<div id="page">
	        <div id="company-header">
	        	<div id="company-name"><a href="<?php echo $this->url('home'); ?>">Acme Corp.</a></div>
	        	<ul id="topmost-navigation">
	        		<li><?php echo $this->translate('Settings'); ?></li>
	        		<li><a href="<?php echo $this->url('account', array('action' => 'index')); ?>"><?php echo $this->translate('Account'); ?></a></li>
	        		<li><a href="<?php echo $this->url('logout');?>"><?php echo $this->translate('Logout'); ?></a></li>
	        	</ul>
	        </div>
	        <div class="container">
	            <?php echo $this->content; ?>
	            <hr>
	            <footer>
	                <p>&copy; 2005 - <?php echo date('Y') ?> by Zend Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
	            </footer>
	        </div> <!-- /container -->
	    </div><!-- #page --> 
        <?php echo $this->inlineScript() ?>
    </body>
</html>
